/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as LimitbreakRouteImport } from './routes/limitbreak'
import { Route as fullCoworkingRouteImport } from './routes/(full)/coworking'
import { Route as fullEmoteRainRouteImport } from './routes/(full)/emote-rain'
import { Route as fullOmnibarRouteImport } from './routes/(full)/omnibar'
import { Route as DebugAlertStackRouteImport } from './routes/debug/alert-stack'
import { Route as DebugEventsRouteImport } from './routes/debug/events'
import { Route as DebugHudRouteImport } from './routes/debug/hud'
import { Route as DebugHudStylesRouteImport } from './routes/debug/hud-styles'
import { Route as DebugIronmonRouteImport } from './routes/debug/ironmon'
import { Route as DebugMachinesRouteImport } from './routes/debug/machines'
import { Route as DebugServerRouteImport } from './routes/debug/server'
import { Route as DebugTranscriptionRouteImport } from './routes/debug/transcription'
import { Route as TelestratorIndexRouteImport } from './routes/telestrator/index'
import { Route as TelestratorOutputRouteImport } from './routes/telestrator/output'

const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitbreakRoute = LimitbreakRouteImport.update({
  id: '/limitbreak',
  path: '/limitbreak',
  getParentRoute: () => rootRouteImport,
} as any)
const fullCoworkingRoute = fullCoworkingRouteImport.update({
  id: '/(full)/coworking',
  path: '/coworking',
  getParentRoute: () => rootRouteImport,
} as any)
const fullEmoteRainRoute = fullEmoteRainRouteImport.update({
  id: '/(full)/emote-rain',
  path: '/emote-rain',
  getParentRoute: () => rootRouteImport,
} as any)
const fullOmnibarRoute = fullOmnibarRouteImport.update({
  id: '/(full)/omnibar',
  path: '/omnibar',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugAlertStackRoute = DebugAlertStackRouteImport.update({
  id: '/debug/alert-stack',
  path: '/debug/alert-stack',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugEventsRoute = DebugEventsRouteImport.update({
  id: '/debug/events',
  path: '/debug/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugHudRoute = DebugHudRouteImport.update({
  id: '/debug/hud',
  path: '/debug/hud',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugHudStylesRoute = DebugHudStylesRouteImport.update({
  id: '/debug/hud-styles',
  path: '/debug/hud-styles',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugIronmonRoute = DebugIronmonRouteImport.update({
  id: '/debug/ironmon',
  path: '/debug/ironmon',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugMachinesRoute = DebugMachinesRouteImport.update({
  id: '/debug/machines',
  path: '/debug/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugServerRoute = DebugServerRouteImport.update({
  id: '/debug/server',
  path: '/debug/server',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugTranscriptionRoute = DebugTranscriptionRouteImport.update({
  id: '/debug/transcription',
  path: '/debug/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const TelestratorIndexRoute = TelestratorIndexRouteImport.update({
  id: '/telestrator/',
  path: '/telestrator/',
  getParentRoute: () => rootRouteImport,
} as any)
const TelestratorOutputRoute = TelestratorOutputRouteImport.update({
  id: '/telestrator/output',
  path: '/telestrator/output',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/audio': typeof AudioRoute
  '/limitbreak': typeof LimitbreakRoute
  '/coworking': typeof fullCoworkingRoute
  '/emote-rain': typeof fullEmoteRainRoute
  '/omnibar': typeof fullOmnibarRoute
  '/debug/alert-stack': typeof DebugAlertStackRoute
  '/debug/events': typeof DebugEventsRoute
  '/debug/hud': typeof DebugHudRoute
  '/debug/hud-styles': typeof DebugHudStylesRoute
  '/debug/ironmon': typeof DebugIronmonRoute
  '/debug/machines': typeof DebugMachinesRoute
  '/debug/server': typeof DebugServerRoute
  '/debug/transcription': typeof DebugTranscriptionRoute
  '/telestrator/output': typeof TelestratorOutputRoute
  '/telestrator/': typeof TelestratorIndexRoute
}
export interface FileRoutesByTo {
  '/audio': typeof AudioRoute
  '/limitbreak': typeof LimitbreakRoute
  '/coworking': typeof fullCoworkingRoute
  '/emote-rain': typeof fullEmoteRainRoute
  '/omnibar': typeof fullOmnibarRoute
  '/debug/alert-stack': typeof DebugAlertStackRoute
  '/debug/events': typeof DebugEventsRoute
  '/debug/hud': typeof DebugHudRoute
  '/debug/hud-styles': typeof DebugHudStylesRoute
  '/debug/ironmon': typeof DebugIronmonRoute
  '/debug/machines': typeof DebugMachinesRoute
  '/debug/server': typeof DebugServerRoute
  '/debug/transcription': typeof DebugTranscriptionRoute
  '/telestrator/output': typeof TelestratorOutputRoute
  '/telestrator': typeof TelestratorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/audio': typeof AudioRoute
  '/limitbreak': typeof LimitbreakRoute
  '/(full)/coworking': typeof fullCoworkingRoute
  '/(full)/emote-rain': typeof fullEmoteRainRoute
  '/(full)/omnibar': typeof fullOmnibarRoute
  '/debug/alert-stack': typeof DebugAlertStackRoute
  '/debug/events': typeof DebugEventsRoute
  '/debug/hud': typeof DebugHudRoute
  '/debug/hud-styles': typeof DebugHudStylesRoute
  '/debug/ironmon': typeof DebugIronmonRoute
  '/debug/machines': typeof DebugMachinesRoute
  '/debug/server': typeof DebugServerRoute
  '/debug/transcription': typeof DebugTranscriptionRoute
  '/telestrator/output': typeof TelestratorOutputRoute
  '/telestrator/': typeof TelestratorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/audio'
    | '/limitbreak'
    | '/coworking'
    | '/emote-rain'
    | '/omnibar'
    | '/debug/alert-stack'
    | '/debug/events'
    | '/debug/hud'
    | '/debug/hud-styles'
    | '/debug/ironmon'
    | '/debug/machines'
    | '/debug/server'
    | '/debug/transcription'
    | '/telestrator/output'
    | '/telestrator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/audio'
    | '/limitbreak'
    | '/coworking'
    | '/emote-rain'
    | '/omnibar'
    | '/debug/alert-stack'
    | '/debug/events'
    | '/debug/hud'
    | '/debug/hud-styles'
    | '/debug/ironmon'
    | '/debug/machines'
    | '/debug/server'
    | '/debug/transcription'
    | '/telestrator/output'
    | '/telestrator'
  id:
    | '__root__'
    | '/audio'
    | '/limitbreak'
    | '/(full)/coworking'
    | '/(full)/emote-rain'
    | '/(full)/omnibar'
    | '/debug/alert-stack'
    | '/debug/events'
    | '/debug/hud'
    | '/debug/hud-styles'
    | '/debug/ironmon'
    | '/debug/machines'
    | '/debug/server'
    | '/debug/transcription'
    | '/telestrator/output'
    | '/telestrator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AudioRoute: typeof AudioRoute
  LimitbreakRoute: typeof LimitbreakRoute
  fullCoworkingRoute: typeof fullCoworkingRoute
  fullEmoteRainRoute: typeof fullEmoteRainRoute
  fullOmnibarRoute: typeof fullOmnibarRoute
  DebugAlertStackRoute: typeof DebugAlertStackRoute
  DebugEventsRoute: typeof DebugEventsRoute
  DebugHudRoute: typeof DebugHudRoute
  DebugHudStylesRoute: typeof DebugHudStylesRoute
  DebugIronmonRoute: typeof DebugIronmonRoute
  DebugMachinesRoute: typeof DebugMachinesRoute
  DebugServerRoute: typeof DebugServerRoute
  DebugTranscriptionRoute: typeof DebugTranscriptionRoute
  TelestratorOutputRoute: typeof TelestratorOutputRoute
  TelestratorIndexRoute: typeof TelestratorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limitbreak': {
      id: '/limitbreak'
      path: '/limitbreak'
      fullPath: '/limitbreak'
      preLoaderRoute: typeof LimitbreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(full)/coworking': {
      id: '/(full)/coworking'
      path: '/coworking'
      fullPath: '/coworking'
      preLoaderRoute: typeof fullCoworkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(full)/emote-rain': {
      id: '/(full)/emote-rain'
      path: '/emote-rain'
      fullPath: '/emote-rain'
      preLoaderRoute: typeof fullEmoteRainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(full)/omnibar': {
      id: '/(full)/omnibar'
      path: '/omnibar'
      fullPath: '/omnibar'
      preLoaderRoute: typeof fullOmnibarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/alert-stack': {
      id: '/debug/alert-stack'
      path: '/debug/alert-stack'
      fullPath: '/debug/alert-stack'
      preLoaderRoute: typeof DebugAlertStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/events': {
      id: '/debug/events'
      path: '/debug/events'
      fullPath: '/debug/events'
      preLoaderRoute: typeof DebugEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/hud': {
      id: '/debug/hud'
      path: '/debug/hud'
      fullPath: '/debug/hud'
      preLoaderRoute: typeof DebugHudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/hud-styles': {
      id: '/debug/hud-styles'
      path: '/debug/hud-styles'
      fullPath: '/debug/hud-styles'
      preLoaderRoute: typeof DebugHudStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/ironmon': {
      id: '/debug/ironmon'
      path: '/debug/ironmon'
      fullPath: '/debug/ironmon'
      preLoaderRoute: typeof DebugIronmonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/machines': {
      id: '/debug/machines'
      path: '/debug/machines'
      fullPath: '/debug/machines'
      preLoaderRoute: typeof DebugMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/server': {
      id: '/debug/server'
      path: '/debug/server'
      fullPath: '/debug/server'
      preLoaderRoute: typeof DebugServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/transcription': {
      id: '/debug/transcription'
      path: '/debug/transcription'
      fullPath: '/debug/transcription'
      preLoaderRoute: typeof DebugTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telestrator/': {
      id: '/telestrator/'
      path: '/telestrator'
      fullPath: '/telestrator/'
      preLoaderRoute: typeof TelestratorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telestrator/output': {
      id: '/telestrator/output'
      path: '/telestrator/output'
      fullPath: '/telestrator/output'
      preLoaderRoute: typeof TelestratorOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AudioRoute: AudioRoute,
  LimitbreakRoute: LimitbreakRoute,
  fullCoworkingRoute: fullCoworkingRoute,
  fullEmoteRainRoute: fullEmoteRainRoute,
  fullOmnibarRoute: fullOmnibarRoute,
  DebugAlertStackRoute: DebugAlertStackRoute,
  DebugEventsRoute: DebugEventsRoute,
  DebugHudRoute: DebugHudRoute,
  DebugHudStylesRoute: DebugHudStylesRoute,
  DebugIronmonRoute: DebugIronmonRoute,
  DebugMachinesRoute: DebugMachinesRoute,
  DebugServerRoute: DebugServerRoute,
  DebugTranscriptionRoute: DebugTranscriptionRoute,
  TelestratorOutputRoute: TelestratorOutputRoute,
  TelestratorIndexRoute: TelestratorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
